.TH "MYNOTES" "1" "April 2017" "mynotes 2.1.0" ""
.SH NAME
MyNotes \- Sticky notes/post-it
.SH SYNOPSIS
.B mynotes
.SH DESCRIPTION
MyNotes is a sticky note application. An icon appears in the system tray
and from it you can create and manage your sticky notes. Notes can be
organized in categories and you can set a default color for each category.
Checkboxes and images can be incorporated in the notes. If your desktop
environment supports compositing, the opacity of the notes can be modified.
.SH AUTHOR
MyNotes is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the SourceForge page of the project
\fBhttps://sourceforge.net/p/my-notes/tickets/\fR 
or send an email to <j_4321@protonmail.com>.
