.TH "MYNOTES" "1" "August 2018" "mynotes 2.4.0" ""
.SH NAME
MyNotes \- Post-it system tray app
.SH SYNOPSIS
.B mynotes [ \fIoptions\fR ]
.SH DESCRIPTION
MyNotes is a sticky notes/post-it application. Notes are created using
the system tray icon. They can be organized in categories and each
category has a color. Images, checkboxes and a few predefined symbols
can be inserted in the notes. The style of the text can be changed
(alignment, style).
.SH OPTIONS
.TP
.BR \-\-show-all
Launch MyNotes if not already running and show all notes.
.TP
.BR \-\-hide-all
Launch MyNotes if not already running and hide all notes.
.SH AUTHOR
MyNotes is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the Github page of the project
\fBhttps://github.com/j4321/MyNotes/issues\fR
or send an email to <j_4321@protonmail.com>.
