#! /usr/bin/python3
# -*- coding:Utf-8 -*-
"""
My Notes - Sticky notes/post-it
Copyright 2016-2018 Juliette Monsel <j_4321@protonmail.com>

My Notes is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

My Notes is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


Main
"""


import os
import sys
import traceback
import signal
from tkinter import Tk
from tkinter.ttk import Style
from mynoteslib.constants import save_config, PIDFILE
from mynoteslib.app import App
from mynoteslib.messagebox import showerror
import logging

# vérifie si mynotes est déjà lancé
pid = str(os.getpid())

if os.path.isfile(PIDFILE):
    with open(PIDFILE) as fich:
        old_pid = fich.read().strip()
    if os.path.exists("/proc/%s" % old_pid):
        if '--show-all' in sys.argv:
            # send signal to mynotes to show all notes
            os.kill(int(old_pid), signal.SIGUSR1)
            sys.exit()
        elif '--hide-all' in sys.argv:
            # send signal to mynotes to hide all notes
            os.kill(int(old_pid), signal.SIGUSR2)
            sys.exit()
        else:
            # MyNotes is already runnning
            root = Tk()
            root.withdraw()
            s = Style(root)
            s.theme_use("clam")
            showerror(_("Error"), _("MyNotes is already running, if not delete ~/.mynotes/mynotes.pid."))
            sys.exit()
    else:
        # it is an old pid file (certainly due to session logout then login)
        os.remove(PIDFILE)
open(PIDFILE, 'w').write(pid)
try:
    app = App(*sys.argv[1:])
    app.mainloop()
except Exception as e:
    showerror(_("Error"), str(type(e)), traceback.format_exc(), True)
finally:
    try:
        app.save()
        save_config()
        os.unlink(PIDFILE)
        logging.shutdown()
    except Exception:
        pass
