#! /usr/bin/python3
# -*- coding:Utf-8 -*-
"""
My Notes - Sticky notes/post-it
Copyright 2016-2017 Juliette Monsel <j_4321@protonmail.com>

My Notes is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

My Notes is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


Main
"""


import os
import sys
import traceback
from tkinter import Tk
from tkinter.ttk import Style
from mynoteslib.constantes import save_config
from mynoteslib.app import App
from mynoteslib.messagebox import showerror
import logging

# vérifie si mynotes est déjà lancé
pid = str(os.getpid())
pidfile = "/tmp/mynotes.pid"

if os.path.isfile(pidfile):
    with open(pidfile) as fich:
        old_pid = fich.read().strip()
    if os.path.exists("/proc/%s" % old_pid):
        # MyNotes is already runnning
        root = Tk()
        root.withdraw()
        s = Style(root)
        s.theme_use("clam")
        showerror(_("Error"), _("MyNotes is already running. If not deletes /tmp/mynotes.pid"))
        sys.exit()
    else:
        # it is an old pid file (certainly due to session logout then login)
        os.remove(pidfile)
open(pidfile, 'w').write(pid)
try:
    app = App()
    app.mainloop()
except Exception as e:
    showerror(_("Error"), str(e), traceback.format_exc(), True)
finally:
    try:
        app.save()
        save_config()
        os.unlink(pidfile)
        logging.shutdown()
    except Exception:
        pass
